//
//  OrgGlossaryView.swift
//  lecsy
//
//  組織メンバー限定: 組織用語集の閲覧・検索画面
//

import SwiftUI

struct OrgGlossaryView: View {
    @StateObject private var orgService = OrganizationService.shared
    @State private var terms: [GlossaryTerm] = []
    @State private var isLoading = false
    @State private var searchText = ""
    @State private var selectedLanguage = ""

    private let languages: [(code: String, name: String)] = [
        ("", "All Languages"),
        ("ja", "Japanese"), ("en", "English"), ("es", "Spanish"),
        ("zh", "Chinese"), ("ko", "Korean"), ("fr", "French"),
        ("de", "German"), ("pt", "Portuguese"), ("it", "Italian"),
        ("ru", "Russian"), ("ar", "Arabic"), ("hi", "Hindi"),
    ]

    var filteredTerms: [GlossaryTerm] {
        var result = terms
        if !searchText.isEmpty {
            let query = searchText.lowercased()
            result = result.filter {
                $0.term.lowercased().contains(query) ||
                $0.definition.lowercased().contains(query)
            }
        }
        return result
    }

    var body: some View {
        VStack(spacing: 0) {
            // Header
            VStack(spacing: 12) {
                HStack {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Organization Glossary")
                            .font(.system(.title3, design: .rounded, weight: .bold))
                        if let org = orgService.organization {
                            Text(org.name)
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }
                    Spacer()
                    Text("\(terms.count) terms")
                        .font(.caption)
                        .foregroundColor(.secondary)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)
                        .background(Color(.systemGray6))
                        .cornerRadius(8)
                }

                // Search
                HStack(spacing: 8) {
                    HStack {
                        Image(systemName: "magnifyingglass")
                            .foregroundColor(.secondary)
                        TextField("Search terms...", text: $searchText)
                            .font(.subheadline)
                    }
                    .padding(.horizontal, 10)
                    .padding(.vertical, 8)
                    .background(Color(.systemGray6))
                    .cornerRadius(10)

                    Picker("Language", selection: $selectedLanguage) {
                        ForEach(languages, id: \.code) { lang in
                            Text(lang.code.isEmpty ? "All" : lang.code.uppercased()).tag(lang.code)
                        }
                    }
                    .pickerStyle(.menu)
                }
            }
            .padding()

            Divider()

            // Terms list
            if isLoading {
                Spacer()
                ProgressView("Loading glossary...")
                    .font(.subheadline)
                Spacer()
            } else if filteredTerms.isEmpty {
                Spacer()
                VStack(spacing: 8) {
                    Image(systemName: "book.closed")
                        .font(.system(size: 36))
                        .foregroundColor(.secondary.opacity(0.5))
                    Text(searchText.isEmpty ? "No terms yet" : "No matching terms")
                        .font(.subheadline)
                        .foregroundColor(.secondary)
                    if searchText.isEmpty {
                        Text("Glossary terms generated by teachers will appear here")
                            .font(.caption)
                            .foregroundColor(.secondary.opacity(0.7))
                            .multilineTextAlignment(.center)
                    }
                }
                Spacer()
            } else {
                ScrollView {
                    LazyVStack(spacing: 8) {
                        ForEach(filteredTerms) { term in
                            GlossaryTermRow(term: term)
                        }
                    }
                    .padding()
                }
            }
        }
        .navigationTitle("Glossary")
        .navigationBarTitleDisplayMode(.inline)
        .task {
            await loadTerms()
        }
        .onChange(of: selectedLanguage) { _, _ in
            Task { await loadTerms() }
        }
        .refreshable {
            await loadTerms()
        }
    }

    private func loadTerms() async {
        isLoading = true
        terms = await orgService.fetchGlossary(
            language: selectedLanguage.isEmpty ? nil : selectedLanguage,
            search: nil
        )
        isLoading = false
    }
}

// MARK: - Term Row

struct GlossaryTermRow: View {
    let term: GlossaryTerm
    @State private var isExpanded = false

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            // Term header
            HStack {
                Text(term.term)
                    .font(.system(.subheadline, design: .rounded, weight: .semibold))
                Spacer()
                HStack(spacing: 4) {
                    Text(term.language.uppercased())
                        .font(.system(.caption2, design: .monospaced, weight: .medium))
                        .foregroundColor(.secondary)
                        .padding(.horizontal, 6)
                        .padding(.vertical, 2)
                        .background(Color(.systemGray5))
                        .cornerRadius(4)
                    if let category = term.category {
                        Text(category)
                            .font(.caption2)
                            .foregroundColor(.emerald)
                            .padding(.horizontal, 6)
                            .padding(.vertical, 2)
                            .background(Color.green.opacity(0.1))
                            .cornerRadius(4)
                    }
                }
            }

            // Definition
            Text(term.definition)
                .font(.caption)
                .foregroundColor(.secondary)
                .lineLimit(isExpanded ? nil : 2)

            if term.definition.count > 100 {
                Button(isExpanded ? "Show less" : "Show more") {
                    withAnimation { isExpanded.toggle() }
                }
                .font(.caption2)
                .foregroundColor(.blue)
            }
        }
        .padding(12)
        .background(Color(.systemBackground))
        .cornerRadius(12)
        .shadow(color: .black.opacity(0.03), radius: 4, y: 1)
    }
}

// Emerald color extension
private extension Color {
    static let emerald = Color(red: 0.2, green: 0.6, blue: 0.4)
}
